name: Build QR Generator Installers 🐹

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-installers:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      
      - name: Configurar JDK 21 (incluimos jpackage cuy) 
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dando permisos a Gradle
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Ejecutar Shadowjar
        run: ./gradlew shadowJar
      
      - name: Generar EXE para Windows
        if: runner.os == 'Windows'
        run: |
          # 1. Buscamos el nombre exacto del archivo JAR cuy
          $jarPath = Get-ChildItem build/libs/*-all.jar | Select-Object -First 1
          $jarName = $jarPath.Name
          Write-Host "El JAR encontrado es: $jarName"
          
          # 2. Ejecutamos jpackage usando esa variable
          jpackage --input build/libs `
            --name QRGenerator `
            --main-jar $jarName `
            --main-class MainKt `
            --type exe `
            --app-version 1.0.0 `
            --win-dir-chooser `
            --win-menu `
            --icon "installer/icono-cuy.ico" `
            --dest dist
            
      - name: Generador DMG para Mac
        if: runner.os == 'macOS'
        run: |
          # 1. Buscamos el nombre exacto del archivo JAR dentro de build/libs
          JAR_NAME=$(ls build/libs | grep "all.jar" | head -n 1)
          echo "El JAR encontrado es: $JAR_NAME"
          
          # 2. Ejecutamos jpackage usando esa variable
          jpackage --input build/libs \
            --name QRGenerator \
            --main-jar "$JAR_NAME" \
            --main-class MainKt \
            --type dmg \
            --app-version 1.0.0 \
            --icon "installer/icono-cuy.icns" \
            --dest dist
            
      - name: Subiendo instalador cuyico para Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: QRGenerator-windows
          path: dist/*.exe
          retention-days: 5

      - name: Subiendo instalador cuyico para Mac
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: QRGenerator-macos
          path: dist/*.dmg
          retention-days: 5
          
      
      
